// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xdhdzohiqlfrhmvwzhoe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhkaGR6b2hpcWxmcmhtdnd6aG9lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1MTI4NTMsImV4cCI6MjA2MTA4ODg1M30.K9jwowhtUV6-qVH0mOdeDqjQ04CSzBVQ8y8wvce9Wvw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);